name: Shellcheck Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  shellcheck:
    name: Run Shellcheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Check for shell scripts
        run: |
          if ! find ./sh/linux -type f -name "*.sh" | grep -q .; then
            echo "No shell scripts found to lint. Exiting."
            exit 0
          fi

      - name: Run Shellcheck and save output
        run: |
          set -x
          mkdir -p logs
          find ./sh/linux -type f -name "*.sh" -exec shellcheck {} + > logs/shellcheck.log || true

      - name: Upload Shellcheck logs
        uses: actions/upload-artifact@v4
        with:
          name: shellcheck-logs
          path: logs/shellcheck.log
